[package]
name = "approportionment"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "approportionment"
path = "rust/main.rs"

# [profile.release]
# debug = 1  # Turn on for profiling
# No difference observed in profiling, but need more rigorous benchmarking
# lto = true
# codegen-units = 1
# panic = "abort"
# strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
statrs = "0.16.0"
serde_dhall = "0.12.0"
serde = { version = "1.0.148", features = ["derive"] }
indicatif = "0.17.2"
rayon = "1.6.0"
arrow = "28.0.0"

