name: site

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install wasm pack
        run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          wasm-pack build --target web -- --features wasm
          cd typescript
          npm ci
          npm run build
          cp -r dist /tmp

      - name: Deploy to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          rm -f *
          cp /tmp/dist/* .
          git commit -a -m "Update site"
          git push

