name: site

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm pack
        run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          wasm-pack build --target web -- --features wasm
          cd typescript
          npm ci
          npm run build
          cp -r dist /tmp

      - name: Deploy to gh-pages branch
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          rm -rf *
          cp /tmp/dist/* .
          EXIT_CODE=0
          git commit -a -m "Update site" || EXIT_CODE=$?
          if [[ $EXIT_CODE -ne 0 ]]; then
            git push 'https://git:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git' HEAD:gh-pages
          fi
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

