name: site

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install wasm pack
        run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          wasm-pack build --target web -- --features wasm
          cd typescript
          npm ci
          npm run build
          cd dist
          chmod 777 *

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: typescript/dist

      - name: Deploy
        id: deployment
        run: actions/deploy-pages@v1
